# The URL the site will be built for
base_url = "https://julian-haas.de"

theme = "anatole-zola"
default_language = "en"

compile_sass = true
ignored_content = ["*.xcf"]

[extra]
show_navigation = false

[extra.social]
github = "haaase"
twitter = "haaase"
lastfm = "couchpotato321"
mail = "haas[ät]cs[dot]tu-darmstadt[dot]de"

[languages.en]
title = "Julian Haas"
# description = "Julian Haas' Homepage"

[languages.en.translations]
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
next_page = "Next Page"
last_page = "Last Page"
contact = "Contact"
